In [1]:
import pandas as pd
import numpy as np
import itertools
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer,HashingVectorizer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('news.csv', index_col = None)
df

,Unnamed: 0,title,text,label
0,8476,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,10294,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,3608,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,10142,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,875,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL
...,...,...,...,...
6330,4490,State Department says it can't find emails fro...,The State Department told the Republican Natio...,REAL
6331,8062,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,FAKE
6332,8622,Anti-Trump Protesters Are Tools of the Oligarc...,Anti-Trump Protesters Are Tools of the Oligar...,FAKE
6333,4021,"In Ethiopia, Obama seeks progress on peace, se...","ADDIS ABABA, Ethiopia —President Obama convene...",REAL
6334,4330,Jeb Bush Is Suddenly Attacking Trump. Here's W...,Jeb Bush Is Suddenly Attacking Trump. Here's W...,REAL

In [3]:
#removing unwanted column
dataset = df.drop("Unnamed: 0", axis=1)
dataset

,title,text,label
0,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL
...,...,...,...
6330,State Department says it can't find emails fro...,The State Department told the Republican Natio...,REAL
6331,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,FAKE
6332,Anti-Trump Protesters Are Tools of the Oligarc...,Anti-Trump Protesters Are Tools of the Oligar...,FAKE
6333,"In Ethiopia, Obama seeks progress on peace, se...","ADDIS ABABA, Ethiopia —President Obama convene...",REAL
6334,Jeb Bush Is Suddenly Attacking Trump. Here's W...,Jeb Bush Is Suddenly Attacking Trump. Here's W...,REAL

In [4]:
#independent and dependent variable split.
y = dataset['label']

In [5]:
#train test split
X_train,X_test,y_train,y_test = train_test_split(dataset['text'],y, test_size = 0.33, random_state = 53)

In [6]:
X_train

2576
1539    Report Copyright Violation Do you think there ...
5163    The election in 232 photos, 43 numbers and 131...
2615    Email Ever wonder what’s on the mind of today’...
4270    Wells Fargo is Rotting from the Top Down Wells...
                              ...
662     —Debby Borza stood before a wall of photos of ...
3261    Presumptive Republican nominee Donald Trump ha...
5883    December's job growth numbers are in, and they...
2933    In a wide-ranging discussion, Trump also said ...
797     Top officials of the Cruz campaign are convinc...
Name: text, Length: 4244, dtype: object

In [7]:
#Conversion of text to number(vectors) 
hashing = HashingVectorizer(stop_words='english',n_features=5000,alternate_sign=False)
hashing_train = hashing.fit_transform(X_train)
print(hashing_train)
hashing_test = hashing.transform(X_test)

  (1, 48)	0.2672612419124244
  (1, 292)	0.1336306209562122
  (1, 335)	0.2672612419124244
  (1, 667)	0.1336306209562122
  (1, 1070)	0.1336306209562122
  (1, 1208)	0.1336306209562122
  (1, 1410)	0.1336306209562122
  (1, 1562)	0.1336306209562122
  (1, 1579)	0.2672612419124244
  (1, 1838)	0.1336306209562122
  (1, 1856)	0.1336306209562122
  (1, 1932)	0.2672612419124244
  (1, 2603)	0.1336306209562122
  (1, 2789)	0.1336306209562122
  (1, 2953)	0.1336306209562122
  (1, 2976)	0.2672612419124244
  (1, 3002)	0.2672612419124244
  (1, 3488)	0.1336306209562122
  (1, 3857)	0.1336306209562122
  (1, 4045)	0.1336306209562122
  (1, 4197)	0.5345224838248488
  (1, 4340)	0.1336306209562122
  (1, 4559)	0.1336306209562122
  (2, 197)	0.3333333333333333
  (2, 1353)	0.3333333333333333
  :	:
  (4243, 4261)	0.028149476494978783
  (4243, 4262)	0.1688968589698727
  (4243, 4283)	0.028149476494978783
  (4243, 4340)	0.05629895298995757
  (4243, 4366)	0.028149476494978783
  (4243, 4447)	0.028149476494978783
  (4243, 4455)	0.028149476494978783
  (4243, 4464)	0.028149476494978783
  (4243, 4495)	0.028149476494978783
  (4243, 4508)	0.028149476494978783
  (4243, 4520)	0.028149476494978783
  (4243, 4562)	0.028149476494978783
  (4243, 4571)	0.028149476494978783
  (4243, 4589)	0.028149476494978783
  (4243, 4665)	0.05629895298995757
  (4243, 4690)	0.028149476494978783
  (4243, 4707)	0.028149476494978783
  (4243, 4763)	0.028149476494978783
  (4243, 4868)	0.028149476494978783
  (4243, 4895)	0.028149476494978783
  (4243, 4916)	0.028149476494978783
  (4243, 4971)	0.028149476494978783
  (4243, 4978)	0.028149476494978783
  (4243, 4981)	0.1407473824748939
  (4243, 4993)	0.028149476494978783

In [8]:
print(hashing_train.toarray())

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.04428074 0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]

In [9]:
# model creation using classification algorithm 
clf = RandomForestClassifier(n_estimators=100,max_features='sqrt',random_state=42)
clf.fit(hashing_train,y_train) 
pred = clf.predict(hashing_test)
#Evaluating using accuracy,confusion matrix and classification report
score = metrics.accuracy_score(y_test, pred)
print("accuracy: %0.3f" % score)
cm = metrics.confusion_matrix(y_test,pred,labels=['FAKE','REAL'])
print("\nConfusion matrix:\n",cm)
from sklearn.metrics import classification_report
report=classification_report(y_test, pred)
print("\nClassification_report:\n",report)

accuracy: 0.894

Confusion matrix:
 [[922  86]
 [135 948]]

Classification_report:
               precision    recall  f1-score   support

        FAKE       0.87      0.91      0.89      1008
        REAL       0.92      0.88      0.90      1083

    accuracy                           0.89      2091
   macro avg       0.89      0.90      0.89      2091
weighted avg       0.90      0.89      0.89      2091

In [10]:
#predictions
dataset['text'][1]

'Google Pinterest Digg Linkedin Reddit Stumbleupon Print Delicious Pocket Tumblr \nThere are two fundamental truths in this world: Paul Ryan desperately wants to be president. And Paul Ryan will never be president. Today proved it. \nIn a particularly staggering example of political cowardice, Paul Ryan re-re-re-reversed course and announced that he was back on the Trump Train after all. This was an aboutface from where he was a few weeks ago. He had previously declared he would not be supporting or defending Trump after a tape was made public in which Trump bragged about assaulting women. Suddenly, Ryan was appearing at a pro-Trump rally and boldly declaring that he already sent in his vote to make him President of the United States. It was a surreal moment. The figurehead of the Republican Party dosed himself in gasoline, got up on a stage on a chilly afternoon in Wisconsin, and lit a match. . @SpeakerRyan says he voted for @realDonaldTrump : “Republicans, it is time to come home” https://t.co/VyTT49YvoE pic.twitter.com/wCvSCg4a5I \n— ABC News Politics (@ABCPolitics) November 5, 2016 \nThe Democratic Party couldn’t have asked for a better moment of film. Ryan’s chances of ever becoming president went down to zero in an instant. In the wreckage Trump is to leave behind in his wake, those who cravenly backed his campaign will not recover. If Ryan’s career manages to limp all the way to 2020, then the DNC will have this tape locked and loaded to be used in every ad until Election Day. \nThe ringing endorsement of the man he clearly hates on a personal level speaks volumes about his own spinelessness. Ryan has postured himself as a “principled” conservative, and one uncomfortable with Trump’s unapologetic bigotry and sexism. However, when push came to shove, Paul Ryan – like many of his colleagues – turned into a sniveling appeaser. After all his lofty tak about conviction, his principles were a house of cards and collapsed with the slightest breeze. \nWhat’s especially bizarre is how close Ryan came to making it through unscathed. For months the Speaker of the House refused to comment on Trump at all. His strategy seemed to be to keep his head down, pretend Trump didn’t exist, and hope that nobody remembered what happened in 2016. Now, just days away from the election, he screwed it all up. \nIf 2016’s very ugly election has done any good it’s by exposing the utter cowardice of the Republicans who once feigned moral courage. A reality television star spit on them, hijacked their party, insulted their wives, and got every last one of them to kneel before him. What a turn of events. \nFeatured image via Twitter'

In [11]:
hashing_train[1]

<1x5000 sparse matrix of type '<class 'numpy.float64'>'
	with 23 stored elements in Compressed Sparse Row format>

In [12]:
hashing = HashingVectorizer(stop_words='english',n_features=5000)
hashing_train = hashing.fit_transform(X_train)

In [13]:
X_train[[1]]

1    Google Pinterest Digg Linkedin Reddit Stumbleu...
Name: text, dtype: object

In [16]:
clf.predict(hashing_train[4])

array(['FAKE'], dtype=object)